version: 2.1

executors:
  python:
    docker:
      - image: circleci/python:3.8.2
  aws:
    docker:
      - image: amazon/aws-cli:latest

jobs:
  python_setup:
    executor: python
    steps:
      - checkout
      # TODO: install requirements without boto3
      - run:
          command: pip install requests -t python
      - run:
          command: zip -r python.zip python
      - persist_to_workspace:
          root: .
          paths:
            - python.zip

  bundle_zip:
    executor: python
    steps:
      - checkout
      - run:
          command: zip -r bundle.zip main.py bundler
      - persist_to_workspace:
          root: .
          paths:
            - bundle.zip

  update_layer:
    executor: aws
    steps:
      - run: yum update -y && yum install -y tar gzip
      - attach_workspace:
          at: .
      - run:
          command: >
            aws lambda publish-layer-version
            --layer-name musicbot-bundler
            --zip-file fileb://python.zip
            --compatible-runtimes python3.8
            --quiet

  update_lambda:
    executor: aws
    steps:
      - run: yum update -y && yum install -y tar gzip
      - attach_workspace:
          at: .
      - run:
          command: >
            aws lambda update-function-code
            --function-name musicbot-bundler
            --zip-file fileb://bundle.zip
            --publish
            --quiet

workflows:
  main:
    jobs:
      - python_setup
      - bundle_zip
      - update_lambda:
          requires:
            - bundle_zip
      - update_layer:
          requires:
            - python_setup
